import {
  getSessionInfo,
  getSessionMessages,
  type SessionMessage,
} from "@anthropic-ai/claude-agent-sdk";
import {
  ExternalSessionImportError,
  type IsoDateTime,
  isToolLifecycleItemType,
  type ProviderInstanceId,
} from "@lecturn/contracts";
import * as DateTime from "effect/DateTime";
import * as Effect from "effect/Effect";

import {
  classifyToolItemType,
  claudeForkResumeState,
  extractAssistantTextBlocks,
  titleForTool,
} from "../Layers/ClaudeAdapter.ts";
import type { ImportedTranscriptEntry, ProviderInstance } from "../ProviderDriver.ts";
import { ClaudeSessionNotFound, forkClaudeSession } from "./ClaudeSessionFork.ts";

const TOOL_DETAIL_MAX_LENGTH = 200;
const FALLBACK_TITLE_MAX_LENGTH = 200;

const PLACEHOLDER_BY_BLOCK_TYPE: Record<string, string> = {
  image: "[image]",
  document: "[attachment]",
};

// Wrappers Claude Code writes as user lines for things the user never typed:
// slash command plumbing, local command output, injected reminders, background
// task notices, the IDE extension's open-file and selection context. A known-tag list rather than the SDK's "any leading tag" rule,
// so a prompt that opens with pasted markup still imports.
const SYNTHETIC_USER_TEXT =
  /^\s*(?:<(?:command-name|command-message|command-args|local-command-stdout|local-command-stderr|local-command-caveat|bash-input|bash-stdout|bash-stderr|system-reminder|task-notification|user-prompt-submit-hook|ide_opened_file|ide_selection)[\s>]|\[Request interrupted by user|Caveat: The messages below were generated by the user while running local commands|This session is being continued from a previous conversation)/;

// The one input field per tool worth a summary line, most specific first.
// Bodies (`content`, `new_string`, `prompt`, …) are deliberately absent.
const TOOL_DETAIL_FIELDS = [
  "command",
  "cmd",
  "file_path",
  "notebook_path",
  "path",
  "pattern",
  "url",
  "query",
  "description",
] as const;

function contentOf(message: SessionMessage): unknown {
  return (message.message as { content?: unknown } | null | undefined)?.content;
}

function userFragments(content: unknown): Array<string> {
  if (typeof content === "string") return [content];
  if (!Array.isArray(content)) return [];
  return content.flatMap((block: unknown) => {
    if (!block || typeof block !== "object") return [];
    const { type, text } = block as { type?: unknown; text?: unknown };
    if (type === "text") return typeof text === "string" ? [text] : [];
    const placeholder = typeof type === "string" ? PLACEHOLDER_BY_BLOCK_TYPE[type] : undefined;
    return placeholder ? [placeholder] : [];
  });
}

function toolActivities(content: unknown, createdAt: IsoDateTime): Array<ImportedTranscriptEntry> {
  if (!Array.isArray(content)) return [];
  return content.flatMap((block: unknown): Array<ImportedTranscriptEntry> => {
    if (!block || typeof block !== "object") return [];
    const { type, name, input } = block as { type?: unknown; name?: unknown; input?: unknown };
    if (type !== "tool_use" || typeof name !== "string" || name.trim().length === 0) return [];
    const toolInput =
      input && typeof input === "object" ? (input as Record<string, unknown>) : undefined;
    const classified = classifyToolItemType(name, toolInput);
    const hint = TOOL_DETAIL_FIELDS.map((field) => toolInput?.[field]).find(
      (value): value is string => typeof value === "string" && value.trim().length > 0,
    );
    const detail = hint ? `${name}: ${hint.trim().replaceAll(/\s+/g, " ")}` : name;
    return [
      {
        kind: "activity",
        // What the live path projects for a finished tool call.
        tone: "tool",
        activityKind: "tool.completed",
        summary: titleForTool(classified),
        itemType: isToolLifecycleItemType(classified) ? classified : "dynamic_tool_call",
        detail:
          detail.length > TOOL_DETAIL_MAX_LENGTH
            ? `${detail.slice(0, TOOL_DETAIL_MAX_LENGTH - 1)}…`
            : detail,
        createdAt,
      },
    ];
  });
}

/**
 * Pure: what `getSessionMessages` returned, as the provider-neutral transcript
 * an imported thread shows: chronological and summary-level, never a tool
 * input payload or a result body. Sidechain, system, tool-result-only,
 * synthetic and empty lines are dropped. `fallbackMs` orders messages that
 * carry no timestamp; only relative order matters, the history builder
 * re-clamps.
 */
export function convertClaudeSessionMessages(
  messages: ReadonlyArray<SessionMessage>,
  fallbackMs: number,
): ReadonlyArray<ImportedTranscriptEntry> {
  const entries: Array<ImportedTranscriptEntry> = [];
  let previousMs = fallbackMs - messages.length;

  for (const message of messages) {
    // `timestamp` is on the runtime object but missing from the SDK's type.
    const parsedMs = Date.parse(String((message as { timestamp?: unknown }).timestamp));
    previousMs = Number.isNaN(parsedMs) ? previousMs + 1 : parsedMs;
    const createdAt = DateTime.formatIso(DateTime.makeUnsafe(previousMs));

    if (message.parent_tool_use_id || message.parent_agent_id || message.type === "system") {
      continue;
    }

    const content = contentOf(message);
    if (message.type === "user") {
      const fragments = userFragments(content).filter((text) => text.trim().length > 0);
      const prompts = fragments.filter((text) => !SYNTHETIC_USER_TEXT.test(text));
      // Tool results and lines the user never typed leave no prompt.
      if (prompts.length > 0) {
        entries.push({ kind: "message", role: "user", text: prompts.join("\n\n"), createdAt });
      }
      continue;
    }

    // Claude Code's own stand-ins ("No response requested.", API error text).
    if ((message.message as { model?: unknown } | null | undefined)?.model === "<synthetic>") {
      continue;
    }
    const text = (typeof content === "string" ? [content] : extractAssistantTextBlocks(message))
      .join("\n\n")
      .trim();
    // A thinking-only line adds nothing.
    if (text.length > 0) entries.push({ kind: "message", role: "assistant", text, createdAt });
    entries.push(...toolActivities(content, createdAt));
  }

  return entries;
}

/**
 * Builds `ProviderInstance.importExternalSession` for the server process's own
 * Claude home: forks the session natively (whole, beside the source, which is
 * never written) and reads the FORK back, so the imported history is exactly
 * what the model resumes with. The source is read first, so a session with
 * nothing to show fails before a fork file exists. The SDK readers follow `process.env`, which is
 * why this shares the lister's default-home condition; all three calls are
 * injectable so tests never read a real home.
 */
export function makeClaudeExternalSessionImporter(options: {
  readonly instanceId: ProviderInstanceId;
  readonly configDir: string;
  readonly forkSession?: typeof forkClaudeSession;
  readonly getSessionMessages?: typeof getSessionMessages;
  readonly getSessionInfo?: typeof getSessionInfo;
}): NonNullable<ProviderInstance["importExternalSession"]> {
  const fork = options.forkSession ?? forkClaudeSession;
  const readMessages = options.getSessionMessages ?? getSessionMessages;
  const readInfo = options.getSessionInfo ?? getSessionInfo;
  return Effect.fn("importClaudeExternalSession")(function* (input) {
    const unreadable = (cause: unknown) =>
      new ExternalSessionImportError({
        providerInstanceId: options.instanceId,
        sessionId: input.sessionId,
        reason: cause instanceof ClaudeSessionNotFound ? "session-not-found" : "unreadable",
        cause,
      });

    // Read before forking: the fork retitles itself "<title> (fork)".
    const info = yield* Effect.tryPromise({
      try: () => readInfo(input.sessionId),
      catch: unreadable,
    });
    const now = DateTime.toEpochMillis(yield* DateTime.now);
    const hasMessage = (entries: ReadonlyArray<ImportedTranscriptEntry>) =>
      entries.some((entry) => entry.kind === "message");
    const sourceMessages = yield* Effect.tryPromise({
      try: () => readMessages(input.sessionId),
      catch: unreadable,
    });
    // The SDK reads a missing session as no lines at all; that case is left
    // to the fork, which tells a missing session from an empty one.
    if (
      sourceMessages.length > 0 &&
      !hasMessage(convertClaudeSessionMessages(sourceMessages, now))
    ) {
      return yield* new ExternalSessionImportError({
        providerInstanceId: options.instanceId,
        sessionId: input.sessionId,
        reason: "empty-session",
      });
    }
    // No `cwd`: the SDK rejects a fork whose `dir` is not the source's own
    // project, and a fork written beside its source resumes from any cwd.
    const forked = yield* Effect.tryPromise({
      try: () =>
        fork({
          sourceSessionId: input.sessionId,
          environment: { CLAUDE_CONFIG_DIR: options.configDir },
        }),
      catch: unreadable,
    });
    const messages = yield* Effect.tryPromise({
      try: () => readMessages(forked.sessionId),
      catch: unreadable,
    });

    const entries = convertClaudeSessionMessages(messages, now);
    const firstPrompt = entries
      .flatMap((entry) =>
        entry.kind === "message" && entry.role === "user" ? [entry.text] : [],
      )[0]
      ?.trim()
      .replaceAll(/\s+/g, " ");
    return {
      resumeCursor: claudeForkResumeState(forked.sessionId),
      title:
        (info?.customTitle || info?.summary)?.trim() ||
        (firstPrompt && firstPrompt.length > FALLBACK_TITLE_MAX_LENGTH
          ? `${firstPrompt.slice(0, FALLBACK_TITLE_MAX_LENGTH - 1)}…`
          : firstPrompt) ||
        "",
      cwd: info?.cwd?.trim() || input.cwd,
      transcript: entries,
    };
  });
}
