// @effect-diagnostics nodeBuiltinImport:off - Standalone build-time notice generator, not an application service.
import * as NodeFS from "node:fs";
import * as NodeURL from "node:url";

const root = new URL("../", import.meta.url);
const sources = [
  "NOTICE.md",
  "LICENSE",
  "apps/web/THIRD_PARTY_NOTICES.md",
  "native/libghostty-vt/LICENSE",
  "apps/web/src/terminal/ghostty/fonts/LICENSE",
  "apps/mobile/modules/t3-composer-editor/LICENSE",
  "apps/mobile/modules/t3-markdown-text/LICENSE",
  "apps/mobile/modules/t3-terminal/THIRD_PARTY_NOTICES.md",
  "licenses/Apache-2.0.txt",
];
const notices = sources
  .map((source) => `${source}\n\n${NodeFS.readFileSync(new URL(source, root), "utf8").trim()}`)
  .join("\n\n---\n\n");
const output = new URL("packages/shared/src/legalNotices.ts", root);
const generated = `// Generated by scripts/generate-legal-notices.ts. Do not edit directly.\nexport const LECTURN_LEGAL_NOTICES =\n  ${JSON.stringify(notices + "\n")};\n`;
if (process.argv.includes("--check")) {
  if ((await import(output.href)).LECTURN_LEGAL_NOTICES !== notices + "\n") {
    throw new Error("Bundled legal notices are stale. Run node scripts/generate-legal-notices.ts.");
  }
} else {
  NodeFS.writeFileSync(output, generated);
}
process.stdout.write(
  `Legal notices ${process.argv.includes("--check") ? "verified" : "generated"}: ${NodeURL.fileURLToPath(output)}\n`,
);
